### ISSUE TITLE
服务器Linux下无法选择文件夹

### ISSUE THREAD

**Issue by geoyee** [PaddleCV-SIG/iann#100]
点加载网络参数的时候，会弹出一个窗口让我选择模型参数，但是我点哪个文件夹都没反应，这个是出窗口的时候的信息。
![image](https://user-images.githubusercontent.com/71769312/147663115-d0cf1813-203d-4ff4-b203-368d861aff29.png)目前看起来可能是QT的问题，有下列参考：
- [https://stackoverflow.com/questions/47847739/qfiledialog-gtkdialog-mapped-without-a-transient-parent](https://stackoverflow.com/questions/47847739/qfiledialog-gtkdialog-mapped-without-a-transient-parent)
- [https://forum.qt.io/topic/85997/gtk-warning-for-native-qfiledialog-under-linux](https://forum.qt.io/topic/85997/gtk-warning-for-native-qfiledialog-under-linux)
- [https://stackoverflow.com/questions/44392504/run-python-gtk3-dialog-or-message-dialog-without-no-transient-parent-warning](https://stackoverflow.com/questions/44392504/run-python-gtk3-dialog-or-message-dialog-without-no-transient-parent-warning)

**Comment by geoyee** [comment]
@linhandev 韩哥空了看看呢，郑院士遇到这个问题。
@Youssef-Harby hello youssef, you can look at this if you are interested. In Linux, when we click to "load network parameters", a dialog will display for us to select model parameters, but we can't pushed to any folder. This image is the information, i think this is a problem in QT.

**Comment by yharby** [comment]
Thanks @geoyee, I will look at this

**Comment by yharby** [comment]
@geoyee , I cannot reproduce the problem, working just fine in my Ubuntu 20.04 VM
![ubuntuEISeg](https://user-images.githubusercontent.com/13020265/147689596-3d47d17d-cb89-45a3-986c-d2327554c4cc.gif)

**Comment by geoyee** [comment]
> @geoyee , I cannot reproduce the problem, working just fine in my Ubuntu 20.04 VM ![ubuntuEISeg](https://user-images.githubusercontent.com/13020265/147689596-3d47d17d-cb89-45a3-986c-d2327554c4cc.gif)

no problem, this problem has been solved by @linhandev : Just use QT's file chooser instead of the original GTK.

**Comment by linhandev** [comment]
solved with [this commit](https://github.com/PaddleCV-SIG/EISeg/commit/e5389aa01f3c732f7b1183d8a682c708ad099738)
