### ISSUE TITLE
影像标注之后，多边形变为矩形

### ISSUE THREAD

**Issue by chaochunbuaimei** [PaddleCV-SIG/iann#101]
**bug描述**
利用建筑物标注模型，空格结束标注，多边形变为矩形

**截屏**
如果
![INML_OK28116CIKTG$D%14Q](https://user-images.githubusercontent.com/78142932/147719035-9fb0f6c0-5490-468a-8552-9ee3c7288f65.png)
![$S{@3FLKX1R%27C$9%% N](https://user-images.githubusercontent.com/78142932/147719046-9bb572d0-0d22-43d8-b4c6-e95bd1f189cf.png)

**运行环境（请尽量填写，这可以帮助我们定位问题）：**
 - 系统： [win10 虚拟机]
 - 安装方式：[e.g. 克隆代码]
 - 软件版本：[0.4.1]

**Comment by geoyee** [comment]
你可以把那个建筑边界简化关闭就可以了，现在这个简化在某些场景下效果还不好
