### ISSUE TITLE
最新版0.4.0 有windows exe么

### ISSUE THREAD

**Issue by Enn29** [PaddleCV-SIG/iann#106]
最新版0.4.0 有windows exe么，还是说直接在0.3版本上替换文件就可以了

**Comment by geoyee** [comment]
不好意思没有的，没有提供

**Comment by Enn29** [comment]
这个后续会提供么，我有试着用qpt打包，运行时会报错，方便解决一下么？
![image](https://user-images.githubusercontent.com/63645468/154874283-2d7269fc-09df-44cc-8a7b-b59141885ec7.png)

**Comment by geoyee** [comment]
> 这个后续会提供么，我有试着用qpt打包，运行时会报错，方便解决一下么？ ![image](https://user-images.githubusercontent.com/63645468/154874283-2d7269fc-09df-44cc-8a7b-b59141885ec7.png)

抱歉后面不提供打包了，之前有个打包的项目我找了找不见了~或许你可以在QPT的repo下提issue

**Comment by geoyee** [comment]
我找到了，试试这个 [https://github.com/geoyee/eiseg2exe](https://github.com/geoyee/eiseg2exe)

**Comment by Enn29** [comment]
> 我找到了，试试这个 https://github.com/geoyee/eiseg2exe

好的，谢谢
