### ISSUE TITLE
plugin\remotesensing\raster.py  line123 遥感图像显示为黑色

### ISSUE THREAD

**Issue by yangweiguang213** [PaddleCV-SIG/iann#111]
**bug描述**
请大致描述出错的现象，在什么情况下或操作过程中遇到，在上述条件下是否总是出现等。
float32型tif（0~1）会将数据全部替换为0，显示图像为黑色。

**解决方法**
rgb.append(np.uint16(self.src_data.read(b))) --> rgb.append(self.src_data.read(b))

**Comment by geoyee** [comment]
> **bug描述** 请大致描述出错的现象，在什么情况下或操作过程中遇到，在上述条件下是否总是出现等。 float32型tif（0~1）会将数据全部替换为0，显示图像为黑色。
> 
> **解决方法** rgb.append(np.uint16(self.src_data.read(b))) --> rgb.append(self.src_data.read(b))

确实，大佬可以提个pr参与贡献一下 😄

**Comment by geoyee** [comment]
感谢你的贡献 😄
