### ISSUE TITLE
无法导入GDAL

### ISSUE THREAD

**Issue by ChenQiang-CN** [PaddleCV-SIG/iann#115]
# 已按照要求安装相应环境，在打开TIF数据时，仍提示“无法导入GDAL”

![image](https://user-images.githubusercontent.com/60353417/168509705-6348a480-eda3-44d5-bbad-8319de5e4aa3.png)

# 导入GDAL正常
![image](https://user-images.githubusercontent.com/60353417/168509796-d288c70a-1307-4a7b-93ba-403a3c4ae9c0.png)

**Comment by geoyee** [comment]
请问可以提供下报错的截图吗
