### ISSUE TITLE
eiseg宫格标注

### ISSUE THREAD

**Issue by YasinFu** [PaddleCV-SIG/iann#116]
大尺寸图片标注是自动跳出是否宫格，每次关闭太麻烦

在设置里可以直接关闭宫格，这样可以不根据尺寸提示是否宫格标注

**Comment by geoyee** [comment]
收到，感谢您的建议

**Comment by geoyee** [comment]
[这里](https://github.com/PaddleCV-SIG/EISeg/commit/4b4ded827679e9185c98b3f0b34dc64e6f0760fa)应该可以了，可以试试现在ok吗，在`功能`最下面可以选择时候检查大小，不开启的话，如果打开了宫格工作区就默认使用，没打开宫格工作区就默认不使用

**Comment by YasinFu** [comment]
感谢，源码下载安装后已可用。请问pip的库何时更新，目前为了方便依赖库安装，我们这边其他人都是用pip安装的。

**Comment by geoyee** [comment]
pypi的是paddleseg下面的，与这个还有点不同，所以下次更新的时候加上

**Comment by YasinFu** [comment]
好的👌
