### ISSUE TITLE
加载模型后闪退

### ISSUE THREAD

**Issue by YQisme** [PaddleCV-SIG/iann#120]
D:\anaconda3\lib\site-packages\win32\lib\pywintypes.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp, sys, os
qt.qpa.fonts: Unable to enumerate family ' "Droid Sans Mono Dotted for Powerline" '
qt.qpa.fonts: Unable to enumerate family ' "Droid Sans Mono Slashed for Powerline" '
qt.qpa.fonts: Unable to enumerate family ' "Roboto Mono Medium for Powerline" '
qt.qpa.fonts: Unable to enumerate family ' "Ubuntu Mono derivative Powerline" '
OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
QObject::~QObject: Timers cannot be stopped from another thread

**Comment by geoyee** [comment]
可以参考这个试试？
[https://blog.csdn.net/weixin_43823786/article/details/124525625](https://blog.csdn.net/weixin_43823786/article/details/124525625)
[https://blog.csdn.net/m0_50736744/article/details/121799432](https://blog.csdn.net/weixin_43823786/article/details/124525625)（方法二）

**Comment by Leon-Brant** [comment]
> 可以参考这个试试？ https://blog.csdn.net/weixin_43823786/article/details/124525625 [https://blog.csdn.net/m0_50736744/article/details/121799432](https://blog.csdn.net/weixin_43823786/article/details/124525625)（方法二）

这里面讲述的方法并不奏效，我在网上查了一些资料，eiseg加载模型后闪退是因为anaconda安装的其他环境中也存在libiomp5md.dll这个动态库文件。假如你安装的虚拟环境比较多的话，这个动态库文件甚至不止有一个。我的建议是不要删除别的虚拟环境下的libiomp5md.dll，而是应该把Anaconda\envs\paddle\Library\bin路径下的libiomp5md.dll删掉。我尝试后发现重新打开eiseg，加载模型后不再闪退。

**Comment by geoyee** [comment]
> > 可以参考这个试试？ https://blog.csdn.net/weixin_43823786/article/details/124525625 [https://blog.csdn.net/m0_50736744/article/details/121799432](https://blog.csdn.net/weixin_43823786/article/details/124525625)（方法二）
> 
> 这里面讲述的方法并不奏效，我在网上查了一些资料，eiseg加载模型后闪退是因为anaconda安装的其他环境中也存在libiomp5md.dll这个动态库文件。假如你安装的虚拟环境比较多的话，这个动态库文件甚至不止有一个。我的建议是不要删除别的虚拟环境下的libiomp5md.dll，而是应该把Anaconda\envs\paddle\Library\bin路径下的libiomp5md.dll删掉。我尝试后发现重新打开eiseg，加载模型后不再闪退。

感谢您的回答

**Comment by YQisme** [comment]
已解决，谢谢
