### ISSUE TITLE
wsl中执行python exe.py出来的软件界面中文显示乱码

### ISSUE THREAD

**Issue by iwannabewater** [PaddleCV-SIG/iann#130]
如下图所示：

![image](https://user-images.githubusercontent.com/82285305/209789129-264afeb7-cb02-40bc-8b08-c74e6b2fd39e.png)

我不知道是wsl的问题还是其他，我更改了wsl的默认编码还是不行，中文还是乱码---
请问我该如何解决！！

**Comment by linhandev** [comment]
没在wsl上遇到过这个问题，不过linux下中文都显示成麻将可能是缺中文字体🤔

**Comment by 724877239** [comment]
我遇到了一样的问题，请问您有解决方案了嘛？
