### ISSUE TITLE
Train module problem: ritm_train.py import error.

### ISSUE THREAD

**Issue by mengmeng716** [PaddleCV-SIG/iann#32]
THX for sharing! 
Import error was found in ritm_train.py
from model.model import (
    get_hrnet_model,
    DistMapsHRNetModel,
    get_deeplab_model,
    get_shufflenet_model,
) 
these modules were not exist in model.py, even in this project. so where can i find these modules, please?

**Comment by mengmeng716** [comment]
Is there any plan for release the training code, please? As it's amazing for common scenes， I want to have a try for other domain adaptation。

**Comment by geoyee** [comment]
> Is there any plan for release the training code, please? As it's amazing for common scenes， I want to have a try for other domain adaptation。

Sorry, the training code will not be released in the near future, but some new parameters will be released soon.
