### ISSUE TITLE
软件闪退

### ISSUE THREAD

**Issue by xmyyzy123** [PaddleCV-SIG/iann#62]
**bug描述**
标注完成以后，关闭软件。再打开软件修改标注， 保存， 切换下一张的时候，软件会闪退

**运行环境（请尽量填写，这可以帮助我们定位问题）：**
 - 系统：Windows
 - 安装方式：克隆代码和Windows exe
 - 软件版本：0.3.0.1和0.3.0.4

**Comment by linhandev** [comment]
您好，可不可以做一个简单的可以复现这个问题的样例数据集。我这边按照描述进行了操作没发现问题🤔@xmyyzy123

**Comment by xmyyzy123** [comment]
标注完成以后，关闭软件。再打开软件(**放大图像**)修改标注， 保存， 切换下一张的时候，软件会闪退 @linhandev 不好意思，是放大图像以后再修改标注

**Comment by xmyyzy123** [comment]
![屏幕截图 2021-11-02 224731](https://user-images.githubusercontent.com/20349084/139870595-e4f01c0e-6070-4820-890f-916c8b2316c5.png)

**Comment by linhandev** [comment]
收到，我应该看到这个问题了，稍等一会

**Comment by linhandev** [comment]
应该是解决了，可以pull一下看看

**Comment by xmyyzy123** [comment]
![屏幕截图 2021-11-02 230400](https://user-images.githubusercontent.com/20349084/139873552-796d49d9-4cfa-4e5e-94ee-d1f973394343.png)

**Comment by xmyyzy123** [comment]
@linhandev 日志好像有问题

**Comment by linhandev** [comment]
欧，那是个昨天新加的功能，我看看

**Comment by linhandev** [comment]
拉一下看看，刚试着弄了一下，我这是linux没报出你那个错

**Comment by xmyyzy123** [comment]
大佬，还是这个错误。上个版本就有这个问题，不过上个版本我把log注释了。

**Comment by linhandev** [comment]
奇怪，等我装个win虚拟机试试吧，你可以再拉一下试试，我把normcase换了个地方，要是还不行就先注掉吧。在app和ui里也有logging，可能需要一起搞掉

**Comment by xmyyzy123** [comment]
还是不行😂，我先注释掉吧

**Comment by xmyyzy123** [comment]
@linhandev  大佬，闪退的问题依然存在，还是一样的错

**Comment by linhandev** [comment]
我丢，要不加个微信我们试试远程一下？

**Comment by linhandev** [comment]
linhandev

**Comment by xmyyzy123** [comment]
已经加了
