### ISSUE TITLE
release/0.4.0 当前存在的部分BUG

### ISSUE THREAD

**Issue by geoyee** [PaddleCV-SIG/iann#64]
## [SELF]
- [x] 切换模型参数后，必须切换图像才能换过来
- [x] 多边形有孔洞可能越界
- [x] 偶见打开后界面混乱，同时加载最近模型也错乱（目前猜测是调试崩溃后打乱了setting的保存）
- [x] #67
- [x] #66
- [x] 单独打开多张图片，快捷键S和F切换的第一次有问题
- [x] 宫格完成后mask和polygon有偏移
- [x] 宫格模式下某些shp保存无法在arcgis中显示（投影问题需要解决）
- [x] 宫格模式多标签问题（全部导出为一个标签了）
- [ ] #70
- [ ] #68
- [x] 增加显示图像的地理信息
- [x] 打开图像报错（存在.xxx.jpg类似格式的文件）
- [x] GPU/TensorRT加载问题（框架版本问题）
- [x] 保留最大联通块推理，生成的多边形仍包含所有块
- [x] 多次关闭和选择图像后，地理信息被清除
- [x] #71
- [x] 导出shp多边形未闭合
- [x] 导出tif波段数不对（为原始图像波段数）
- [x] 【讨论】导出图像名的大小写与原始图像名不一致（Linux大小写敏感会不会在训练时匹配不上文件 @linhandev）
- [x] jpg等医疗图像调整窗宽等闪退
- [x] 【完善】英语翻译支持
- [x] 【完善】pip打包
- [ ] 【完善】exe打包
- [x] 【完善】md文档

## [QA]
- [x] #74
- [x] #75
- [x] #76
- [x] #77
- [x] #78
- [x] #79
- [x] #80
- [x] #81

**Comment by linhandev** [comment]
加载最近模型貌似不对，没有加载最近那次 @linhandev
删掉原来的config重新跑一下试试

**Comment by geoyee** [comment]
> 加载最近模型貌似不对，没有加载最近那次 @linhandev 删掉原来的config重新跑一下试试

OK是的，那这个没问题了

**Comment by linhandev** [comment]
【讨论】导出图像名的大小写与原始图像名不一致（Linux大小写敏感会不会在训练时匹配不上文件 @linhandev）

会，导出的名字怎么不一致的🤔不记得有改过大小写啊

**Comment by geoyee** [comment]
> 【讨论】导出图像名的大小写与原始图像名不一致（Linux大小写敏感会不会在训练时匹配不上文件 @linhandev）
> 
> 会，导出的名字怎么不一致的🤔不记得有改过大小写啊

在win下面，osp.normcase会把所有的路径转成小写和规范的斜杠，但是win不区分大小写，不知道在linux下面这个osp.normcase是会转换还是保持原样

**Comment by linhandev** [comment]
> > 【讨论】导出图像名的大小写与原始图像名不一致（Linux大小写敏感会不会在训练时匹配不上文件 @linhandev）
> > 
> > 会，导出的名字怎么不一致的🤔不记得有改过大小写啊
> 
> 在win下面，osp.normcase会把所有的路径转成小写和规范的斜杠，但是win不区分大小写，不知道在linux下面这个osp.normcase是会转换还是保持原样

linux下不变，大写还是大写的

**Comment by geoyee** [comment]
> > > 【讨论】导出图像名的大小写与原始图像名不一致（Linux大小写敏感会不会在训练时匹配不上文件 @linhandev）
> > > 会，导出的名字怎么不一致的🤔不记得有改过大小写啊
> > 
> > 
> > 在win下面，osp.normcase会把所有的路径转成小写和规范的斜杠，但是win不区分大小写，不知道在linux下面这个osp.normcase是会转换还是保持原样
> 
> linux下不变，大写还是大写的

那应该可以不管这个了
