### ISSUE TITLE
win 软件包加载模型参数寻找的是.pdparams文件

### ISSUE THREAD

**Issue by somTian** [PaddleCV-SIG/iann#84]
**bug描述**
win 软件包加载模型参数寻找的是.pdparams文件
而下载的模型文件后缀为.pdiparams
选中不了

**复现方法**
从这里下载的最新EISeg。解压后双击启动程序.exe即可运行程序。
选择加载模型寻找的是.pdparams文件

**截屏**
![image](https://user-images.githubusercontent.com/19942099/142147918-9a9756cb-039c-4fd2-94dc-4defe2f8c6cb.png)

**运行环境（请尽量填写，这可以帮助我们定位问题）：**
 - 系统：Windows
 - 安装方式：Windows exe
 - 软件版本：EISeg0.3.0.1

**Comment by busbyjrj** [comment]
+1，将.pdiparams重命名为pdparams后，直接崩溃了

**Comment by geoyee** [comment]
@somTian @busbyjrj 
在0.3.0中模型是使用的动态图，现在0.4.0版本已经全部改成静态图了，所以配合下载的模型都是静态的模型和参数。
抱歉现在README没有更新，后续可能也不准备维护exe的了，建议配置好环境使用。
