### ISSUE TITLE
巨大的图像分块读取

### ISSUE THREAD

**Issue by linhandev** [PaddleCV-SIG/iann#87]
有说读1g以上遥感的，除了推理要分块，读取可能也需要分块

**Comment by geoyee** [comment]
> 有说读1g以上遥感的，除了推理要分块，读取可能也需要分块

收到，我研究下rasterio看看，貌似可以实现这个功能

**Comment by geoyee** [comment]
目前已经基本可以完成分块读取了，不会全部加载到内存再分块。这个部分我放在rasterio这个分支下面，因为很多部分重新改了，还有些问题等做完了没问题了再merge过来。目前还有的问题（留待22号解决）：
- [x] 切换图像和切换宫格的问题
- [x] 宫格完成后的清理问题
- [x] shp的保存问题
