### ISSUE TITLE
tool

### ISSUE THREAD

**Issue by geoyee** [PaddleCV-SIG/iann#88]
韩哥 @linhandev ， tool下面的脚本换一种方式吗？这个写的[说明](https://github.com/PaddleCV-SIG/EISeg/blob/develop/docs/tools.md)还要吗？之前有人提需要转格式到paddlex的

**Comment by linhandev** [comment]
删掉的脚本不是干那个事的，到paddlex我们不需要转换吧，pdx不是能读coco。之前那个脚本就做了个数据集划分，那个pdx也能做

**Comment by geoyee** [comment]
> 删掉的脚本不是干那个事的，到paddlex我们不需要转换吧，pdx不是能读coco。之前那个脚本就做了个数据集划分，那个pdx也能做

了解，不过有一个是分jpg/png那个的（其实也就是重新移动了下位置和新建文件），不是coco的，这个也不用了哇，那我就把说明里面的这个删了
![](https://user-images.githubusercontent.com/71769312/141392744-f1a27774-2714-43a2-8808-2fc14a5a6b5a.png)

**Comment by linhandev** [comment]
我记得当时看是一个没啥用，一个的功能pdx也能做来着

**Comment by geoyee** [comment]
> 我记得当时看是一个没啥用，一个的功能pdx也能做来着

ok了解
