### ISSUE TITLE
带有多边形的图像缩放后loadImage闪退

### ISSUE THREAD

**Issue by geoyee** [PaddleCV-SIG/iann#90]
![image](https://user-images.githubusercontent.com/71769312/144229898-950502b1-90fd-4596-bd50-587a356fc799.png)

**Comment by geoyee** [comment]
出现于在进行多边形修改或者删除多边形并重新点击出多边形后

**Comment by geoyee** [comment]
同 #93

**Comment by geoyee** [comment]
目前对问题的复现在于：缩放（主要是放大）图像进行点的编辑（移动/删除）然后缩放回接近原大小，之后切换图像基本会崩

**Comment by geoyee** [comment]
> 目前对问题的复现在于：缩放（主要是放大）图像进行点的编辑（移动/删除）然后缩放回接近原大小，之后切换图像基本会崩

进一步确认问题：当图像存在多边形，放大图像出现边界框滑块后，缩小图像至边界框滑块消失，此时切换崩溃

**Comment by geoyee** [comment]
> > 目前对问题的复现在于：缩放（主要是放大）图像进行点的编辑（移动/删除）然后缩放回接近原大小，之后切换图像基本会崩
> 
> 进一步确认问题：当图像存在多边形，放大图像出现边界框滑块后，缩小图像至边界框滑块消失，此时切换崩溃

不止如此，缩小放大，以及不出现滑块依旧可能崩溃，崩溃分两种情况，一种是闪退不报错，一种是未响应

**Comment by geoyee** [comment]
目前确定是在loadimage完毕后退出，缩放之后可以保存，没有错，但是不管保不保存，只要缩放过后，尝试换图像就会崩溃

**Comment by geoyee** [comment]
> 目前确定是在loadimage完毕后退出，缩放之后可以保存，没有错，但是不管保不保存，只要缩放过后，尝试换图像就会崩溃

但是loadimage中print显示代码都正常运行完成

**Comment by geoyee** [comment]
问题复现步骤：
1. 加载一个图像文件夹
2. 标注第一张图像，按住ctrl+滚轮反复放大缩小（较大尺度的改变）
3. 保存结果
4. S/F或点击列表切换下一张图像
5. 崩溃

**Comment by linhandev** [comment]
试了一下没复现，明天继续

**Comment by yharby** [comment]
I think we can close this issue now, pull the new updates and try to reproduce the issue again , if the app crashes please give us a feedback.
Thank You!
