### ISSUE TITLE
加载模型参数，交互窗口直接退出

### ISSUE THREAD

**Issue by AlexXFM** [PaddleCV-SIG/iann#99]
请帮忙分析如下bug，如何解决：
模型参数文件后缀是“pdiparams”，而窗口加载模型的识别格式是“pdparams”；将模型参数文件格式后缀修改为“pdparams”后，使用窗口加载模型，接着窗口直接关闭推出，标注工具无法使用
![image](https://user-images.githubusercontent.com/30640779/147632682-70e167ae-3b62-4ca7-83cd-f44598746b4b.png)

**Comment by geoyee** [comment]
> 请帮忙分析如下bug，如何解决： 模型参数文件后缀是“pdiparams”，而窗口加载模型的识别格式是“pdparams”；将模型参数文件格式后缀修改为“pdparams”后，使用窗口加载模型，接着窗口直接关闭推出，标注工具无法使用 ![image](https://user-images.githubusercontent.com/30640779/147632682-70e167ae-3b62-4ca7-83cd-f44598746b4b.png)

`pdiparams`是静态图的参数，`pdparams`是动态图的参数。在0.4.0以上EISeg已经都改为使用静态图了。所以请升级你的EISeg到最新版，你可以直接拉取develop分支下的。如果还有什么问题欢迎继续提issue

**Comment by AlexXFM** [comment]
感谢解答！
